#Remember to make nic spesifics if needed

- name: Install ufw
  apt:
    name: ufw
    state: present
  become: true

- name: Reset ufw
  ufw:
    state: reset
  become: true

- name: Deny incoming by default
  ufw:
    default: deny
    direction: incoming
  become: true

- name: Allow outgoing by default
  ufw:
    default: allow
    direction: outgoing
  become: true

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH
  become: true

# ---------------------------
# BASIC WEB / SYSTEM SERVICES
# ---------------------------

- name: Allow HTTP and HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 80
    - 443
  become: true

- name: Allow DNS (53 TCP/UDP)
  ufw:
    rule: allow
    port: "53"
    proto: "{{ item }}"
  loop:
    - tcp
    - udp
  become: true

- name: Allow NTP
  ufw:
    rule: allow
    port: "123"
    proto: udp
  become: true

# ---------------------------
# UNIFI REMOTE MANAGEMENT
# ---------------------------

- name: Allow STUN
  ufw:
    rule: allow
    port: "3478"
    proto: udp
  become: true

- name: Allow Remote Access HTTPS
  ufw:
    rule: allow
    port: "443"
    proto: tcp
  become: true

- name: Allow Remote Access support
  ufw:
    rule: allow
    port: "8883"
    proto: tcp
  become: true

- name: Allow Remote Access ingress support
  ufw:
    rule: allow
    port: "5349"
    proto: tcp
  become: true

# ---------------------------
# UNIFI NETWORK CONTROLLER
# ---------------------------

- name: Allow UniFi device inform
  ufw:
    rule: allow
    port: "8080"
    proto: tcp
  become: true

- name: Allow UniFi GUI / API
  ufw:
    rule: allow
    port: "8443"
    proto: tcp
  become: true

- name: Allow Hotspot portals
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 8880
    - 8881
    - 8882
    - 8843
    - 8444
  become: true

- name: Allow speed test
  ufw:
    rule: allow
    port: "6789"
    proto: tcp
  become: true

- name: Allow local DB communication
  ufw:
    rule: allow
    port: "27117"
    proto: tcp
  become: true

- name: Allow UniFi discovery
  ufw:
    rule: allow
    port: "10001"
    proto: udp
  become: true

- name: Allow client fingerprinting
  ufw:
    rule: allow
    port: "10101"
    proto: udp
  become: true

- name: Allow L2 discovery
  ufw:
    rule: allow
    port: "1900"
    proto: udp
  become: true

- name: Allow syslog
  ufw:
    rule: allow
    port: "5514"
    proto: udp
  become: true

- name: Allow SSH 
  ufw:
    rule: allow
    port: "22"
    proto: tcp
  become: true

# ---------------------------
#  ENABLE
# ---------------------------

- name: Enable ufw and logging
  ufw:
    state: enabled
    logging: on
  become: true


